language: go
go:
  - 1.5
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
before_install:
  - go get
  - go get github.com/stretchr/testify/assert
  - go get golang.org/x/tools/cmd/cover
script:
  - go build
  - go test -v -covermode=count -coverprofile=coverage.out ./...
  - go tool cover -func=coverage.out
  - go tool cover -html=coverage.out
